# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
parameters:
  image-name:
    type: enum
    default: "circleci/clojure:openjdk-11-tools-deps"
    enum: ["circleci/clojure:openjdk-11-tools-deps", "circleci/clojure:openjdk-8-tools-deps"]
  cljdoc-analyzer-dep:
    type: string
    default: '{:deps {cljdoc-analyzer {:git/url "https://github.com/cljdoc/cljdoc-analyzer.git" :sha "323343a3d644fed486621032bd0b5a21171e4b09"}}})'
  cljdoc-analyzer-args:
    type: string
    default: '{:project "bidi" :version "2.1.3" :jarpath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.jar" :pompath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.pom"}'

jobs:
  build:
    docker:
      - image: << pipeline.parameters.image-name >>

    steps:
      - run: echo '<< pipeline.parameters.cljdoc-analyzer-dep >>' > /tmp/cache-key

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/tmp/cache-key" }}
          - v1-dependencies- # fallback if not cache found

      - run:
          name: Tools versions
          command: |
            clojure -Sdescribe
            java -version

      - run:
          name: Print build parameters
          command: echo "$CLJDOC_ANALYZER_ARGS"

      - run:
          name: Run analysis
          command: >
            clojure -Sdeps '<< pipeline.parameters.cljdoc-analyzer-dep >>'
            -M -m cljdoc-analyzer.cljdoc-main
            '<< pipeline.parameters.cljdoc-analyzer-args >>'

      - store_artifacts:
          path: /tmp/cljdoc/analysis-out/
          destination: /

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "/tmp/cache-key" }}
